import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Github } from "lucide-react";
import "./globals.css";

import NewNoteFormDrawer from "@/components/NewNoteFormDrawer";
import { Button } from "@/components/ui/button";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="grid h-screen w-full">
          <div className="flex flex-col">
            <header className="sticky top-0 z-10 flex h-[57px] items-center justify-between gap-1 border-b bg-white px-4">
              <Link href="/">
                <h1 className="text-xl font-semibold">Notes App</h1>
              </Link>
              <div className="flex gap-2 ">
                <NewNoteFormDrawer />
                <Link href="https://github.com/NicoCieri" target="_blank">
                  <Button className="mr-2" size="sm">
                    <Github className="mr-2" />
                    NicoCieri
                  </Button>
                </Link>
              </div>
            </header>
            <main className="grid flex-1 overflow-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
